spring:
  application:
    name: subscription

  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 20
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:subs}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

server:
  port: 8080
